"""Global (cross-sectional) features for market-wide indicators."""

from signalflow.ta.global_features.btc_contagion import BTCStressContagionStat
from signalflow.ta.global_features.market import (
    MarketIndexFeature,
    MarketRollingMinFeature,
    MarketRsiFeature,
    MarketVolatilityFeature,
    MarketZscoreFeature,
    compute_global_features,
)
from signalflow.ta.global_features.cross_sectional import (
    AvgPairwiseCorrMarket,
    CrossSectionalAdxRank,
    CrossSectionalAtrRank,
    CrossSectionalBeta,
    CrossSectionalDispersion,
    CrossSectionalRangeRank,
    CrossSectionalRetSkew,
    CrossSectionalReturnAccelRank,
    CrossSectionalReturnRank,
    CrossSectionalRsiRank,
    CrossSectionalVolRank,
    DivergenceFromMarketMedian,
    MarketBreadth,
    PairExcessReturn,
    PairLeadLagCorr,
    RelativeStrengthVsMarket,
)

__all__ = [
    "BTCStressContagionStat",
    "MarketIndexFeature",
    "MarketRollingMinFeature",
    "MarketRsiFeature",
    "MarketVolatilityFeature",
    "MarketZscoreFeature",
    "compute_global_features",
    "AvgPairwiseCorrMarket",
    "CrossSectionalAdxRank",
    "CrossSectionalAtrRank",
    "CrossSectionalBeta",
    "CrossSectionalDispersion",
    "CrossSectionalRangeRank",
    "CrossSectionalRetSkew",
    "CrossSectionalReturnAccelRank",
    "CrossSectionalReturnRank",
    "CrossSectionalRsiRank",
    "CrossSectionalVolRank",
    "DivergenceFromMarketMedian",
    "MarketBreadth",
    "PairExcessReturn",
    "PairLeadLagCorr",
    "RelativeStrengthVsMarket",
]
